### ISSUE TITLE
`syntax error in as` ?

### ISSUE THREAD

**Issue by nguermond** [LPCIC/elpi#106]
The following gives me a very strange error (in elpi 1.13.7):

```prolog
type bar any -> any.

foo (bar (uvar as K)) :- print "hello".

main :- (foo (x \ bar u)).
```
outputs
```Fatal error: syntax error in as```

whereas almost any other input:
```prolog
main :- (foo (x \ bar2 u)).
main :- (foo Y).
main :- (foo (bar u)).
main :- (foo (bar X)).
```
succeeds or fails without error.

Is this expected behavior?

**Comment by nguermond** [comment]
When I replace the line
https://github.com/LPCIC/elpi/blob/4909286fe43cfc1330e9d24bf8be4783bed5a2fb/src/runtime.ml#L1483
with
```ocaml
| _, App(c,arg,_) when c == Global_symbols.asc -> unif matching depth adepth a bdepth arg e
```
similarly to the symmetric case
https://github.com/LPCIC/elpi/blob/4909286fe43cfc1330e9d24bf8be4783bed5a2fb/src/runtime.ml#L1484-L1485
the above example fails as expected and all the tests pass.

Was there perhaps a reason to make `unif` not symmetric?

**Comment by gares** [comment]
unification is not symmetric in the code since one term is on the stack, the clause head contains nodes such as Arg and also as, while the other one is a heap term, no Arg.

as is only allowed in the head of a clause. I'm sloppy in checking it, maybe my code is wrong, but this is the reason for the asymmetry. 

Now that I look at it I guess the code for eta to kick in https://github.com/LPCIC/elpi/blob/4909286fe43cfc1330e9d24bf8be4783bed5a2fb/src/runtime.ml#L1703
and mess with that check. Your goal contains an explicit lambda while the clause head not.

**Comment by gares** [comment]
https://github.com/LPCIC/elpi/blob/4909286fe43cfc1330e9d24bf8be4783bed5a2fb/src/runtime.ml#L1480
Here the list has lenght 2, since the eta code added an extra argument. I will fix it.

**Comment by nguermond** [comment]
Thank you so much for taking the time to address my issues.
Please see my comment https://github.com/LPCIC/elpi/pull/107#issuecomment-909379428.

I am also wondering why I cannot replace 
```prolog 
foo (bar (uvar K Args)) :- print K "@" Args.
```
with
```prolog
foo (bar X) :- (var X K Args), print K "@" Args.
```
because on input
```prolog
main :- (pi x \ (foo (bar (X x)))).
```
this produces the error (on both branches)
```Fatal error: (Data.Term.UVar ( { Data.Term.contents = please extend this printer; rest =  }, 1, 0)) is not a list```
while failing successfully on both inputs:
```prolog
main :- (foo (bar (x \ u))).
main :- (foo (x \ (bar u))).
```

**Comment by gares** [comment]
thanks for the tests, I'll update the PR
