### ISSUE TITLE
Confusing behavior applying a function to `_`

### ISSUE THREAD

**Issue by mb64** [LPCIC/elpi#113]
Here's a simplified version of my code showing the confusing behavior:

```elpi
kind ty type.

type all (ty -> ty) -> ty.
type arr ty -> ty -> ty.
type unit ty.

type apply ty -> ty -> ty -> o.
apply (arr A B) A B.
apply (all T) A B :- apply (T _) A B. % instantiate with a fresh unification variable
```
Running with `elpi ex.elpi <<<'apply (all a\ arr a a) unit B.'` gives the answer
```
Success:
  B = X0
```

If, however, I change the last line to
```elpi
apply (all T) A B :- apply (T Fresh) A B. % instantiate with a fresh unification variable
```
I get a warning about the singleton variable, but my query returns the expected answer:
```
Success:
  B = unit
```

Is this the expected behavior? And what can I write to get it to do the right thing, and also not give a warning? (I tried `_Fresh` but that also gave the wrong answer.)

**Comment by gares** [comment]
So, `_` really means discard (little doc here: https://github.com/LPCIC/elpi/blob/7111c63e3614a1d7d591711bafd29c6ae4fb3fd6/ELPI.md#underscore).

If you write `_Foo` you still mean `_` discard but you are giving a name to help the reader.
If you write `Foo_` you mean `Foo` but you silence the linearity warning that should fire since your `Fresh` variable is only used once (and most of the times this is a typo).

Maybe the warning is not clear enough? It should have suggested you either `_Foo` or `Foo_` giving an hint which is which,

**Comment by gares** [comment]
For the records: `_` makes sense in the head of the clause. Using it in the premises may leave to results which are somewhat unexpected.

**Comment by mb64** [comment]
Yes, that works, thanks! Sorry for the slow response.
