### ISSUE TITLE
Goal ids identical in some cases

### ISSUE THREAD

**Issue by jwintz** [LPCIC/elpi#148]
Hi,

Still concerning the `trace-browser` branch, I may need to clarify the semantic of a `goal_id`. I (surely by mistake) assumed it was unique, and used to rely on it to jump from one card to another in the trace vs code plugin extension, but as it happens, I realised it is not unique, I felt like I should get a clear understanding of its meaning.

For example, the card of `(runtime_id, step_id)` `(0, 2)` contains an `Inference rule` which goal ID is `5`:

https://github.com/LPCIC/elpi/blob/96c4d071194b4c7f20b9d09754c60a8e76922b07/tests/sources/trace.elab.json#L74

... but so does the card `(0, 11)`:

https://github.com/LPCIC/elpi/blob/96c4d071194b4c7f20b9d09754c60a8e76922b07/tests/sources/trace.elab.json#L953

I will surely refactor the trace visualiser to use the `(runtime_id, step_id)` as a unique identifier, but the question remains.

Thanks.

**Comment by gares** [comment]
The goal is the same, but we try different rules on it. This is because the system explores all possibilities.

Each goal borns (as a sibling of a rule) exactly in one place. Each goal may be the subject of more than one card. Maybe clicking on a goal (when it is the subject of a rule) can jump to its creation point, or (when it is a sibling) jump to the first card about it (the next ones should be jumpable via the next successful attempts thing).
