### ISSUE TITLE
Switch building system to dune

### ISSUE THREAD

**Issue by XVilka** [LPCIC/elpi#20]

**Comment by gares** [comment]
Patches are very welcome! I'm sorry but I'm not very familiar with dune.

The only tricky bits I can foresee are:
- first one needs to build ./trace_ppx and then compile the rest
- src/elpi_runtime.ml is compiled twice with two different -for-pack values, and the two resulting objects are both linked in elpi.cmxa. One object, thanks to trace_ppx, has tracing code, while the other has not. (one could also copy the file under a different name and compile it if the current solution is impossible to implement)
- elpi.ml is compiled using an installation of src/* via findlib to a temporary directory (I'm not installing the whole contents of src/, I want to be sure elpi.ml is a regular client hence I cannot add `-I src/` since it would make more files visible).
