### ISSUE TITLE
Not compatible with dune cache

### ISSUE THREAD

**Issue by SkySkimmer** [LPCIC/elpi#72]
With `(cache enabled)` in my `~/.config/dune/config` I got 
~~~
#=== ERROR while compiling elpi.1.11.0 ========================================#
# context     2.0.5 | linux/x86_64 | ocaml-base-compiler.4.07.1 | https://opam.ocaml.org#bc6d04e5
# path        ~/.opam/4.07.1/.opam-switch/build/elpi.1.11.0
# command     ~/.opam/opam-init/hooks/sandbox.sh build make fix-elpi.install
# exit-code   2
# env-file    ~/.opam/log/elpi-109268-97bbf8.env
# output-file ~/.opam/log/elpi-109268-97bbf8.out
### output ###
# dune exec ./fix_elpi_install.exe -- elpi.install
# Error: Error: utimes: /home/gaetan/.cache/dune/db/v2/beacon: Read-only file
# system
# make: *** [Makefile:36: fix-elpi.install] Error 1
~~~
Disabling the cache allowed `opam install elpi` to succeed.

**Comment by gares** [comment]
I've never enabled the cache. The only "weird" thing about fix_elpi_install is that is overwrites a file generated by dune. I've no idea if this can be the problem

**Comment by gares** [comment]
Indeed https://dune.readthedocs.io/en/stable/caching.html?highlight=cache#filesystem-implementation says that they use hard links and that files are dead only.

I see what I can do. The root of the problem is that quite hard to explain, but the result is that I must make two technical executable public, but then I don't want them to be installed. The only way I found was to hack the .install generated by dune. Any better strategy would be welcome.

**Comment by gares** [comment]
Is seems it is an opam issue. Can you confirm that with opam 2.0.7 it works?

**Comment by gares** [comment]
ping @skyskimmer

**Comment by SkySkimmer** [comment]
I don"t know, 2.0.7 isn"t in debian testing yet.

**Comment by rgrinberg** [comment]
>  The root of the problem is quite hard to explain, but the result is that I must make two technical executable public, but then I don't want them to be installed.

The only difference between a public & private executable inside a dune build is wether it exists in `PATH` or not. Are you sure you can't live without a private executable?

We've added a `binaries` field to [env](https://dune.readthedocs.io/en/stable/dune-files.html?highlight=binaries#env) that allows a private executable to also be visible in PATH. Perhaps this is enough? If not, I can discuss your use case with the dune team.

**Comment by gares** [comment]
I'd love to, but IIRC something goes wrong in the dependencies (possibly my fault, but I could not find another way).
Here my setup. In `/src/dune` I have
```
(library
  (name elpi)
  (public_name elpi)
  (preprocess (per_module
    ((action (run ppxfindcache_deriving_std  %{input-file}
                    --cache-file %{dep:.ppcache/API.ml}

```
while in `ppxfindcache/dune` I have
```
(executable
  (name ppxfindcache2)
  (public_name ppxfindcache_deriving_std)
  (modules ppxfindcache2)
  (libraries unix re ppxfindcache_aux
    (select ppxfindcache2.ml from
      (ppx_deriving.std -> ppxfindcache2.useppx.ml)
      (-> ppxfindcache2.cacheonly.ml)))
  (flags -linkall)
)
```
I could not find a way to tell dune to use the private name `ppxfindcache2` *and* still have it built as a dependency of `.ppcache/API.ml`.

Any hints?

**Comment by gares** [comment]
FTR ppxfindcache is a little hack to be able to compile files even if the ppx stack is not around (the cache contains source files pre-processed with the ppx). I'd rather use deriving inline if it was a thing...

**Comment by rgrinberg** [comment]
I tried getting rid of it in #86 

`[@@deriving_inline ]` does exist, but I'm not it will work in your case, since you're using `ppx_deriving.std` rather than janestreet's alternative extensions.

Another option to consider is to write `(rule (mode promote) ..)` to generate your sources. This will allow you to check in the preprocessed sources and use them for releases (when installed through opam), but will try to regenerate the sources using your binary in development (when you clone and do `$ dune build`).

**Comment by gares** [comment]
@SkySkimmer can I close this now?

**Comment by SkySkimmer** [comment]
No, because I'm closing it ;)
